import AppKit
import ApplicationServices
import FlowHelperCore
import Foundation

/// Puts text into the focused app: save the clipboard, set the text, press Cmd+V, and
/// put the clipboard back unless the user has copied something newer in the meantime.
///
/// Used from the main thread only. It never logs the text it handles.
final class PasteTransaction {
    /// A clipboard larger than this is not saved; the transcript then stays on it.
    private static let snapshotByteBudget = 16 * 1024 * 1024
    /// Nor is one that takes longer than this to read. Content another app provides on
    /// demand (a large selection, Universal Clipboard) can take seconds.
    private static let snapshotTimeBudget: TimeInterval = 0.25
    /// After a read this slow, focus may have moved: the destination is checked again.
    private static let slowSnapshot: TimeInterval = 0.3

    /// Tell clipboard managers this entry is temporary and should not be kept in history.
    private static let markerTypes = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
    ].map { NSPasteboard.PasteboardType($0) }

    private struct Pending {
        let pasteId: Int
        /// Nil when the clipboard was too large to save.
        let saved: [[NSPasteboard.PasteboardType: Data]]?
        let changeCount: Int
        let timer: DispatchWorkItem
    }

    private let targets: TargetStore
    private let emit: @Sendable ([String: Any]) -> Void
    private var pending: Pending?

    init(targets: TargetStore, emit: @escaping @Sendable ([String: Any]) -> Void) {
        self.targets = targets
        self.emit = emit
    }

    /// Whether this process may post key events. The rule is `PostAccess`; this reads
    /// the two answers it needs.
    ///
    /// `CGPreflightPostEventAccess` cannot be relied on by itself. Once a process has
    /// asked macOS for the right to post (creating an active key tap does that), the
    /// preflight repeats what it was told then. A helper whose tap was attempted before
    /// Accessibility was granted heard "no" from it for good, and every paste was
    /// refused (2026-10-03). `AXIsProcessTrusted` follows the setting as it changes.
    static func mayPostEvents() -> (allowed: Bool, detail: String) {
        PostAccess.decide(trusted: AXIsProcessTrusted(), preflight: { CGPreflightPostEventAccess() })
    }

    /// Returns the outcome: `pasted`, `targetChanged`, `secureField` or `noPostAccess`.
    /// Anything other than `pasted` leaves the clipboard untouched. `detail` says why:
    /// for `targetChanged`, which part of the destination differs; for `secureField`,
    /// what marked it as one; for `noPostAccess`, what the two permission checks said,
    /// or `keyEvent` when the key press could not be made.
    func paste(pasteId: Int, text: String, targetId: Int?, restoreDelayMs: Int) -> (outcome: String, detail: String?) {
        let access = Self.mayPostEvents()
        guard access.allowed else { return ("noPostAccess", access.detail) }
        // The key press is made before the clipboard is touched: without it nothing can
        // be pasted, and the clipboard must then be left as it is.
        guard let keys = makePasteShortcut() else { return ("noPostAccess", "keyEvent") }

        if let refusal = refusal(for: targetId) { return refusal }

        // Finish any earlier paste first, or its transcript would be saved as "the clipboard".
        settle()

        let pasteboard = NSPasteboard.general
        let readStarted = Date()
        let saved = snapshot(pasteboard)
        if Date().timeIntervalSince(readStarted) > Self.slowSnapshot, let refusal = refusal(for: targetId) {
            return refusal
        }
        pasteboard.prepareForNewContents(with: .currentHostOnly)
        pasteboard.setString(text, forType: .string)
        for marker in Self.markerTypes {
            pasteboard.setData(Data(), forType: marker)
        }
        let changeCount = pasteboard.changeCount

        // Give the pasteboard server a moment before the target app asks for the data.
        usleep(20000)
        keys.down.post(tap: .cgSessionEventTap)
        // Some apps miss a key-up that follows its key-down with no gap.
        usleep(8000)
        keys.up.post(tap: .cgSessionEventTap)

        let timer = DispatchWorkItem { [weak self] in self?.settle() }
        pending = Pending(pasteId: pasteId, saved: saved, changeCount: changeCount, timer: timer)
        DispatchQueue.main.asyncAfter(deadline: .now() + .milliseconds(restoreDelayMs), execute: timer)
        return ("pasted", nil)
    }

    /// Restores the clipboard now if a paste is waiting to. Safe to call at any time.
    func settle() {
        guard let pending else { return }
        self.pending = nil
        pending.timer.cancel()
        emit(HelperProtocol.pasteSettled(pasteId: pending.pasteId, restored: restore(pending)))
    }

    private func restore(_ pending: Pending) -> Bool {
        let pasteboard = NSPasteboard.general
        // A different change count means the user copied something after the paste. Keep theirs.
        guard pasteboard.changeCount == pending.changeCount, let saved = pending.saved else {
            return false
        }
        pasteboard.clearContents()
        let items = saved.map { entry -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in entry {
                item.setData(data, forType: type)
            }
            return item
        }
        if items.isEmpty == false {
            pasteboard.writeObjects(items)
        }
        return true
    }

    /// Why a paste into this destination must be refused, or nil when it may go ahead.
    private func refusal(for targetId: Int?) -> (outcome: String, detail: String?)? {
        if let targetId {
            switch targets.compare(targetId: targetId) {
            case .same: return nil
            case .changed(let what): return ("targetChanged", what)
            case .secure(let why): return ("secureField", why)
            }
        }
        if let why = targets.current()?.secureReason { return ("secureField", why) }
        return nil
    }

    /// The clipboard as it is now, to be put back after the paste. Nil means it could
    /// not be saved (too large, too slow, or unreadable), and the transcript then stays
    /// on the clipboard: putting back a copy that is incomplete would lose what was there.
    private func snapshot(_ pasteboard: NSPasteboard) -> [[NSPasteboard.PasteboardType: Data]]? {
        // Nil here is a failed read, not an empty clipboard.
        guard let pasteboardItems = pasteboard.pasteboardItems else { return nil }
        let deadline = Date().addingTimeInterval(Self.snapshotTimeBudget)
        var total = 0
        var items: [[NSPasteboard.PasteboardType: Data]] = []
        for item in pasteboardItems {
            var entry: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                if Date() > deadline { return nil }
                guard let data = item.data(forType: type) else { continue }
                total += data.count
                if total > Self.snapshotByteBudget { return nil }
                entry[type] = data
            }
            items.append(entry)
        }
        return items
    }

    /// The Cmd+V key press, ready to post, or nil if it cannot be made.
    private func makePasteShortcut() -> (down: CGEvent, up: CGEvent)? {
        let source = CGEventSource(stateID: .hidSystemState)
        let keyCode = KeyLayout.keyCode(for: "v") ?? KeyLayout.qwertyV
        guard let down = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true),
              let up = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false)
        else { return nil }

        for event in [down, up] {
            // Command only, whatever keys the user is physically holding.
            event.flags = .maskCommand
            event.setIntegerValueField(.eventSourceUserData, value: EventTap.ownEventTag)
        }
        return (down, up)
    }
}
