import AppKit
import ApplicationServices
import FlowHelperCore
import Foundation

/// Puts text into the focused app: save the clipboard, set the text, press Cmd+V, and
/// put the clipboard back unless the user has copied something newer in the meantime.
///
/// Used from the main thread only. It never logs the text it handles.
final class PasteTransaction {
    /// Tell clipboard managers this entry is temporary and should not be kept in history.
    private static let markerTypes = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
    ].map { NSPasteboard.PasteboardType($0) }

    private struct Pending {
        let pasteId: Int
        /// Nil when the clipboard could not be saved whole (see `ClipboardSnapshot`).
        let saved: ClipboardSnapshot?
        let changeCount: Int
        let timer: DispatchWorkItem
    }

    private let targets: TargetStore
    private let emit: @Sendable ([String: Any]) -> Void
    private var pending: Pending?

    init(targets: TargetStore, emit: @escaping @Sendable ([String: Any]) -> Void) {
        self.targets = targets
        self.emit = emit
    }

    /// Whether this process may post key events. The rule is `PostAccess`; this reads
    /// the two answers it needs.
    ///
    /// `CGPreflightPostEventAccess` cannot be relied on by itself. Once a process has
    /// asked macOS for the right to post (creating an active key tap does that), the
    /// preflight repeats what it was told then. A helper whose tap was attempted before
    /// Accessibility was granted heard "no" from it for good, and every paste was
    /// refused (2026-10-03). `AXIsProcessTrusted` follows the setting as it changes.
    static func mayPostEvents() -> (allowed: Bool, detail: String) {
        PostAccess.decide(trusted: AXIsProcessTrusted(), preflight: { CGPreflightPostEventAccess() })
    }

    /// Returns the outcome: `pasted`, `targetChanged`, `secureField`, `noPostAccess` or
    /// `expired`. `detail` says why: for `targetChanged`, which part of the destination
    /// differs; for `secureField`, what marked it as one; for `noPostAccess`, what the
    /// two permission checks said, or `keyEvent` when the key press could not be made;
    /// for `expired`, where the time ran out.
    ///
    /// Anything other than `pasted` leaves the clipboard as it was. (One exception: when
    /// the time runs out after the text was written and the clipboard could not be
    /// saved, there is nothing to put back, and the text stays on it.)
    ///
    /// The order of the steps, and when the paste is called off, is `PasteSequence`.
    /// `expiresAtMs` is when the app stops waiting, in milliseconds since the epoch.
    func paste(
        pasteId: Int,
        text: String,
        targetId: Int?,
        restoreDelayMs: Int,
        expiresAtMs: Double? = nil
    ) -> (outcome: String, detail: String?) {
        let pasteboard = NSPasteboard.general
        var keys: (down: CGEvent, up: CGEvent)?
        var saved: ClipboardSnapshot?
        var changeCount = 0

        let steps = PasteSteps(
            now: { Date().timeIntervalSince1970 * 1_000 },
            postAccess: { Self.mayPostEvents() },
            prepareKeys: {
                keys = self.makePasteShortcut()
                return keys != nil
            },
            refusal: { afterWait in self.refusal(for: targetId, afterWait: afterWait) },
            settleEarlierPaste: { self.settle() },
            saveClipboard: { saved = ClipboardSnapshot.capture(pasteboard) },
            writeText: {
                pasteboard.prepareForNewContents(with: .currentHostOnly)
                pasteboard.setString(text, forType: .string)
                for marker in Self.markerTypes {
                    pasteboard.setData(Data(), forType: marker)
                }
                changeCount = pasteboard.changeCount
                // Give the pasteboard server a moment before the target app asks for the data.
                usleep(20000)
            },
            pressKeys: {
                guard let keys else { return }
                keys.down.post(tap: .cgSessionEventTap)
                // Some apps miss a key-up that follows its key-down with no gap.
                usleep(8000)
                keys.up.post(tap: .cgSessionEventTap)
            },
            takeTextBack: {
                self.pending = Pending(
                    pasteId: pasteId, saved: saved, changeCount: changeCount, timer: DispatchWorkItem {}
                )
                self.settle()
            },
            scheduleRestore: {
                let timer = DispatchWorkItem { [weak self] in self?.settle() }
                self.pending = Pending(pasteId: pasteId, saved: saved, changeCount: changeCount, timer: timer)
                DispatchQueue.main.asyncAfter(deadline: .now() + .milliseconds(restoreDelayMs), execute: timer)
            }
        )
        return PasteSequence.run(steps, expiresAtMs: expiresAtMs)
    }

    /// Restores the clipboard now if a paste is waiting to. Safe to call at any time.
    func settle() {
        guard let pending else { return }
        self.pending = nil
        pending.timer.cancel()
        let notRestored = restore(pending)
        emit(HelperProtocol.pasteSettled(
            pasteId: pending.pasteId, restored: notRestored == nil, reason: notRestored
        ))
    }

    /// Puts the saved clipboard back. Returns nil when it did, or why it was left as it
    /// is: `copiedSince` (the user copied something after the paste, and keeps it),
    /// `notSaved` (there was no complete copy to put back, so the pasted text stays on
    /// the clipboard) or `failed` (the pasteboard would not take the copy).
    private func restore(_ pending: Pending) -> String? {
        let pasteboard = NSPasteboard.general
        // A different change count means the user copied something after the paste. Keep theirs.
        guard pasteboard.changeCount == pending.changeCount else { return "copiedSince" }
        guard let saved = pending.saved else { return "notSaved" }
        return saved.restore(to: pasteboard) ? nil : "failed"
    }

    /// Why a paste into this destination must be refused, or nil when it may go ahead.
    private func refusal(for targetId: Int?, afterWait: Bool) -> (outcome: String, detail: String?)? {
        if let targetId {
            switch targets.compare(targetId: targetId, afterWait: afterWait) {
            case .same: return nil
            case .changed(let what): return ("targetChanged", what)
            case .secure(let why): return ("secureField", why)
            }
        }
        guard let now = targets.current() else { return nil }
        // With no recorded destination to ask, the app that was last seen in front is
        // asked whether it still is.
        if afterWait, targets.isFrontmost(now.pid) != true { return ("targetChanged", "app") }
        if let why = now.secureReason { return ("secureField", why) }
        return nil
    }

    /// The Cmd+V key press, ready to post, or nil if it cannot be made.
    private func makePasteShortcut() -> (down: CGEvent, up: CGEvent)? {
        let source = CGEventSource(stateID: .hidSystemState)
        let keyCode = KeyLayout.keyCode(for: "v") ?? KeyLayout.qwertyV
        guard let down = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: true),
              let up = CGEvent(keyboardEventSource: source, virtualKey: keyCode, keyDown: false)
        else { return nil }

        for event in [down, up] {
            // Command only, whatever keys the user is physically holding.
            event.flags = .maskCommand
            event.setIntegerValueField(.eventSourceUserData, value: EventTap.ownEventTag)
        }
        return (down, up)
    }
}
